### PR TITLE
update to 3.8.5

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
@hadim @johanneskoester @mariusvniekerk opinions? Not sure about the implications except that maven 3.8.1 requires java 7.

**Comment by hadim** [comment]
I am not using maven either java much anymore so I don't feel very confident reviewing this PR. I can merge it if you are confident enough on your side. Can you maybe remove me from the maintainer list? And add yourself if you want to?

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

@wolfv did you want to maintain this?

**Comment by hmaarrfk** [comment]
This might be necessary for https://github.com/conda-forge/imagemagick-feedstock/pull/218

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

@conda-forge-admin please restart cis

**Comment by hmaarrfk** [comment]
Not sure why it is not being found :/

**Comment by mariusvniekerk** [comment]
Why is this switching to a src release?

**Comment by hmaarrfk** [comment]
I think they are doing something to change the SHA on the fly. I was just trying to get it download...

**Pull request merged**
