### PR TITLE
try relaxing openjdk pin

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/maven ready for review, with a disclaimer: I don't know what i don't know about maven/jdk version compatibility, but _do_ know some packages are starting to require `openjdk 20`. Does this need a `conda_build_config.yaml` entry to matrix across versions? Ick. Write once, debug everywhere.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by mkitti** [comment]
Did something change with openjdk 20 feedstock?

**Comment by mkitti** [comment]
Is the error in the link below fixed?

https://github.com/conda-forge/maven-feedstock/pull/24#issuecomment-1588465291

**Comment by bollwyvl** [comment]
Success [reported here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=768487&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=13529
)... were the tests then subsequently skipped or something?

Logs excerpt:

```
2023-08-24T18:02:39.3800826Z   + openjdk                    20.0.0  h57928b3_0   conda-forge/win-64     Cached
...
[INFO] --- site:3.12.1:attach-descriptor (attach-descriptor) @ apache-maven ---
[WARNING] Parameter 'localRepository' is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
[INFO] Attaching 'src\site\site.xml' site descriptor with classifier 'site'.
[INFO] 
[INFO] --- assembly:3.6.0:single (create-distro-packages) @ apache-maven ---
[INFO] Reading assembly descriptor: src/main/assembly/bin.xml
[INFO] Building zip: %SRC_DIR%\apache-maven\target\apache-maven-3.9.4-bin.zip
[INFO] Building tar: %SRC_DIR%\apache-maven\target\apache-maven-3.9.4-bin.tar.gz
[INFO] 
[INFO] --- assembly:3.6.0:single (create-distribution-dir) @ apache-maven ---
[INFO] Reading assembly descriptor: src/main/assembly/dir.xml
[INFO] Copying files to %BUILD_PREFIX%\Library\.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Maven 3.9.4:
[INFO] 
[INFO] Apache Maven ....................................... SUCCESS [ 16.584 s]
[INFO] Maven Model ........................................ SUCCESS [ 13.030 s]
[INFO] Maven Artifact ..................................... SUCCESS [  4.997 s]
[INFO] Maven Plugin API ................................... SUCCESS [  2.398 s]
[INFO] Maven Builder Support .............................. SUCCESS [  1.088 s]
[INFO] Maven Model Builder ................................ SUCCESS [ 11.718 s]
[INFO] Maven Settings ..................................... SUCCESS [  0.686 s]
[INFO] Maven Settings Builder ............................. SUCCESS [  1.755 s]
[INFO] Maven Repository Metadata Model .................... SUCCESS [  1.146 s]
[INFO] Maven Artifact Resolver Provider ................... SUCCESS [  8.532 s]
[INFO] Maven Core ......................................... SUCCESS [ 49.197 s]
[INFO] Maven SLF4J Simple Provider ........................ SUCCESS [  3.923 s]
[INFO] Maven Embedder ..................................... SUCCESS [  7.255 s]
[INFO] Maven Compat ....................................... SUCCESS [ 28.764 s]
[INFO] Apache Maven Distribution .......................... SUCCESS [ 44.858 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

```

**Comment by mkitti** [comment]
Closing this in favor of #37

**Pull request closed without merging**
