### PR TITLE
Build from source at version 3.9.2

### PR DESCRIPTION
**Pull request by mkitti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
Fix #3

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
@matthiasdiener and @jakirkham, I have updated the build from source code to version 3.9.2 incorporating elements from #5 to fix #3. I would appreciate a review so that can finally have maven built from source in coda-forge.

This is an important component to include further components of scientific Java in conda-forge. https://scijava.org

**Review by matthiasdiener — APPROVED** [review]
Thanks, this looks good to me! Would you like to add yourself as a maintainer to this package?

**Comment by mkitti** [comment]
Thank you for the invitation. I would love to join as a maintainer. I'll add myself to the meta.yaml. Is there anything else that I should do? Should I skip another CI run?

**Comment by matthiasdiener** [comment]
> I'll add myself to the meta.yaml. Is there anything else that I should do? Should I skip another CI run?

Great! After adding yourself to the meta.yaml, please rerender again, that should be all that's necessary.

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Mark! 🙏

**Pull request merged**
