### PR TITLE
Linux ppc64le/aarch64

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is ready for review @conda-forge/maven @wolfv @hmaarrfk

**Comment by hmaarrfk** [comment]
is maven a pure bash script?

**Comment by matthiasdiener** [comment]
> is maven a pure bash script?

What do you mean? maven is a java app, `mvn` is a bash script that calls java.

**Comment by hmaarrfk** [comment]
got it. so it is likely something with the emulation of openjdk that is broken.

I'm just worried when we "skip a test entirely" to call something working. I've been skipping so many ppc64le tests recently.

If its ok, i'll let marius merge this since he is is an owener of this. I don't know anything about maven.

**Comment by matthiasdiener** [comment]
> got it. so it is likely something with the emulation of openjdk that is broken.
> 
> I'm just worried when we "skip a test entirely" to call something working. I've been skipping so many ppc64le tests recently.

I see your point. Unfortunately, this also segfaults on my local machine when running with qemu. Since there isn't anything compiled though, just copying of files, I think it's quite safe that it will work as long as it works on other systems.

**Pull request merged**
